# Generated by Django 5.0.1 on 2026-02-08 06:45

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatsession_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSessionRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_rating', models.IntegerField(help_text='Overall rating (1-5)')),
                ('agent_friendliness', models.IntegerField(blank=True, help_text='Rating for agent friendliness (1-5)', null=True)),
                ('response_time', models.IntegerField(blank=True, help_text='Rating for response time (1-5)', null=True)),
                ('problem_resolution', models.IntegerField(blank=True, help_text='Rating for problem resolution (1-5)', null=True)),
                ('feedback', models.TextField(blank=True, help_text='Detailed feedback from visitor')),
                ('would_recommend', models.BooleanField(default=False, help_text='Would visitor recommend this service')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When rating was submitted')),
            ],
            options={
                'verbose_name': 'Session Rating',
                'verbose_name_plural': 'Session Ratings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TypingIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When typing started')),
            ],
            options={
                'verbose_name': 'Typing Indicator',
                'verbose_name_plural': 'Typing Indicators',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='chatsession',
            options={'ordering': ['-created_at'], 'verbose_name': 'Chat Session', 'verbose_name_plural': 'Chat Sessions'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at'], 'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
        migrations.AddField(
            model_name='chatsession',
            name='current_page',
            field=models.URLField(blank=True, help_text='Page where chat was initiated', max_length=500),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='department',
            field=models.CharField(blank=True, db_index=True, help_text='Department or category for this chat', max_length=50),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='duration_seconds',
            field=models.IntegerField(default=0, help_text='Total duration of active chat (in seconds)'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='feedback',
            field=models.TextField(blank=True, help_text="Visitor's feedback/comment"),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='internal_notes',
            field=models.TextField(blank=True, help_text='Internal notes for agents (not visible to visitor)'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='last_message_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of last message in this session', null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='message_count',
            field=models.IntegerField(default=0, help_text='Total number of messages in this session'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='previous_agent',
            field=models.ForeignKey(blank=True, help_text='Previous agent before transfer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_agent_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Normal'), (3, 'High'), (4, 'Urgent')], db_index=True, default=2, help_text='Priority level for queue ordering'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='rating',
            field=models.IntegerField(blank=True, help_text="Visitor's rating (1-5 stars)", null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='referrer_url',
            field=models.URLField(blank=True, help_text='URL where visitor came from', max_length=500),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='session_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for this chat session'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='started_at',
            field=models.DateTimeField(blank=True, help_text='When agent joined and chat started', null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='subject',
            field=models.CharField(blank=True, help_text='Subject or title of the chat conversation', max_length=200),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags for this session', max_length=500),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='visitor_email',
            field=models.EmailField(blank=True, help_text="Visitor's email address", max_length=254),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='visitor_ip',
            field=models.GenericIPAddressField(blank=True, help_text="Visitor's IP address", null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='visitor_location',
            field=models.CharField(blank=True, help_text="Visitor's geographic location", max_length=100),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='visitor_name',
            field=models.CharField(blank=True, help_text="Visitor's display name", max_length=100),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='visitor_phone',
            field=models.CharField(blank=True, help_text="Visitor's phone number", max_length=20),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='visitor_user_agent',
            field=models.TextField(blank=True, help_text="Visitor's browser user agent"),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='wait_time_seconds',
            field=models.IntegerField(default=0, help_text='How long visitor waited before agent joined (in seconds)'),
        ),
        migrations.AddField(
            model_name='message',
            name='attachment',
            field=models.FileField(blank=True, help_text='File attachment', null=True, upload_to='chat_attachments/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'pdf', 'doc', 'docx', 'txt', 'zip'])]),
        ),
        migrations.AddField(
            model_name='message',
            name='attachment_name',
            field=models.CharField(blank=True, help_text='Original filename of attachment', max_length=255),
        ),
        migrations.AddField(
            model_name='message',
            name='attachment_size',
            field=models.IntegerField(default=0, help_text='Size of attachment in bytes'),
        ),
        migrations.AddField(
            model_name='message',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When message was deleted', null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Whether message has been deleted'),
        ),
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether message has been read'),
        ),
        migrations.AddField(
            model_name='message',
            name='message_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for this message'),
        ),
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('file', 'File'), ('image', 'Image'), ('system', 'System'), ('transfer', 'Transfer'), ('joined', 'Joined'), ('left', 'Left')], db_index=True, default='text', help_text='Type of message', max_length=20),
        ),
        migrations.AddField(
            model_name='message',
            name='read_at',
            field=models.DateTimeField(blank=True, help_text='When message was read', null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed')], default='sent', help_text='Delivery status of message', max_length=20),
        ),
        migrations.AddField(
            model_name='message',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When message was last updated'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='agent',
            field=models.ForeignKey(blank=True, help_text='Agent handling this chat session', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='closed_at',
            field=models.DateTimeField(blank=True, help_text='When the chat session was closed', null=True),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the chat session was created'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting for Agent'), ('active', 'Active'), ('closed', 'Closed'), ('transferred', 'Transferred'), ('abandoned', 'Abandoned')], db_index=True, default='waiting', help_text='Current status of the chat session', max_length=20),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='visitor',
            field=models.ForeignKey(help_text='Visitor who initiated this chat', on_delete=django.db.models.deletion.CASCADE, related_name='visitor_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(help_text='Text content of the message'),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='When message was sent'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(help_text='User who sent this message', on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='session',
            field=models.ForeignKey(help_text='Chat session this message belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatsession'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['status', 'created_at'], name='chat_chatse_status_8e9421_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['agent', 'status'], name='chat_chatse_agent_i_d229bd_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['visitor', 'created_at'], name='chat_chatse_visitor_283ac4_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['session', 'created_at'], name='chat_messag_session_4940cf_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', 'created_at'], name='chat_messag_sender__b02346_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['is_read', 'session'], name='chat_messag_is_read_14334d_idx'),
        ),
        migrations.AddField(
            model_name='chatsessionrating',
            name='session',
            field=models.OneToOneField(help_text='Chat session being rated', on_delete=django.db.models.deletion.CASCADE, related_name='detailed_rating', to='chat.chatsession'),
        ),
        migrations.AddField(
            model_name='typingindicator',
            name='session',
            field=models.ForeignKey(help_text='Chat session where typing is occurring', on_delete=django.db.models.deletion.CASCADE, related_name='typing_indicators', to='chat.chatsession'),
        ),
        migrations.AddField(
            model_name='typingindicator',
            name='user',
            field=models.ForeignKey(help_text='User who is typing', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='typingindicator',
            unique_together={('session', 'user')},
        ),
    ]
