# Generated by Django 5.0.1 on 2026-02-08 07:02

import uuid
from django.db import migrations


def populate_session_and_message_uuid(apps, schema_editor):
    ChatSession = apps.get_model("chat", "ChatSession")
    Message = apps.get_model("chat", "Message")

    # Populate ChatSession.session_id
    for session in ChatSession.objects.filter(session_id__isnull=True):
        session.session_id = uuid.uuid4()
        session.save(update_fields=["session_id"])

    # Populate Message.message_id
    for message in Message.objects.filter(message_id__isnull=True):
        message.message_id = uuid.uuid4()
        message.save(update_fields=["message_id"])


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_chatsessionrating_typingindicator_and_more"),
    ]

    operations = [
        migrations.RunPython(populate_session_and_message_uuid),
    ]
